export const FETCH_COMBINED_SCHEDULE = "FETCH_COMBINED_SCHEDULE";
export const FETCH_SLOTS = "FETCH_SLOTS";
export const TOGGLE_MODAL = "TOGGLE_MODAL";
export const ADD_CLASS = "ADD_CLASS";
export const UPDATE_CLASS = "UPDATE_CLASS";
