export const GET_MESSAGES = "GET_MESSAGES";
export const UPDATE_NEW_MESSAGE = "UPDATE_NEW_MESSAGE";
export const CREATE_NEW_MESSAGE = "CREATE_NEW_MESSAGE";
export const RECEIVE_NEW_MESSAGE = "RECEIVE_NEW_MESSAGE";
export const REMOVE_MESSAGES = "REMOVE_MESSAGES";
